version: "3"
services:
    db:
        image: postgres:12.2
        volumes:
            - db-data:/var/lib/postgresql/data
        networks:
            - backend
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: sonarqube
    
    sonar:
        image: sonarqube:8.2-community
        ports:
            - 9000:9000
        networks:
            - backend
        environment:
            SONAR_JDBC_URL: jdbc:postgresql://db/sonarqube
            SONAR_JDBC_USERNAE: postgres
            SONAR_JDBC_PASSWORD: postgres
        volumes:
            - sonar-extensions:/opt/sonarqube/extensions
        depends_on:
            - db

volumes:
    db-data:
    sonar-extensions:

networks:
    backend:

